name: Deploy to Fly
on:
  push:
    branches:
      - main
jobs:
  test:
    name: test app
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
    steps:
      - uses: actions/checkout@v3
      - run: apk add --update chromium && apk add build-base
      - run: |
          go version
      - run: |
          go test ./...

  deploy:
    needs: test
    name: deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
